/* confdefs.h */
#define PACKAGE_NAME "HashMap"
#define PACKAGE_TARNAME "hashmap"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "HashMap 1.0"
#define PACKAGE_BUGREPORT "https://github.com/JekasObps"
#define PACKAGE_URL ""
#define PACKAGE "hashmap"
#define VERSION "1.0"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE__BOOL 1
#define HAVE_MALLOC 1
#define HAVE_REALLOC 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMSET 1
